### PR TITLE
Added event on_message function

### PR DESCRIPTION
**Pull request by zoticusbarns**
Added function on_message in newly created commands/messages.py to handle any messages received on the server.

### CODE REVIEW

**Comment by AJTopisano** [comment]
So I wonder what does it do?

**Review by AJTopisano — COMMENTED** [review]
So what does it do ?

**Comment by zoticusbarns** [comment]
> 
> 
> So what does it do ?

It doesn't actually do anything yet. Right now it will log any message received in the server from anyone on the console. But in the future we can add more functions in this code to reply to other ppl's messages. Like my dad bot, if somebody mention something, the bot can reply.

**Comment by AJTopisano** [comment]
Is there a need to log poke.. I wonder

**Review by AJTopisano — APPROVED** [review]
Is there a need to log poke back ?.. everything seems fine anyways

**Comment by zoticusbarns** [comment]
> 
> 
> Is there a need to log poke.. I wonder

More logging gives us more information when debugging errors in the future. I suppose we can change it to `logger.debug`? So it wont show up in the production log?

**Comment by AJTopisano** [comment]
Well let's test it out..

**Pull request merged**
